#include "FileJournal.h"



    /* {src_lang=cpp}*/



FileJournal::FileJournal()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-102-13253627:128108a3c64:-8000:0000000000001164 begin
{
    db = QSqlDatabase::addDatabase("QSQLITE","DROPBOX");

    QString path(QDir::home().path());
    path.append(QDir::separator()).append(".dropbox/dropbox.db");
    path = QDir::toNativeSeparators(path);
    db.setDatabaseName(path);
    if (!db.open())
        qt_message_output(QtDebugMsg,"Error connecting to dropbox.db");

}
// section -64--88-0-102-13253627:128108a3c64:-8000:0000000000001164 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

QList <QString> FileJournal::lastChangedFiles()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-102-13253627:128108a3c64:-8000:0000000000001166 begin
{
   QSqlQuery query("SELECT active_server_path FROM file_journal order by active_sjid desc limit 5",db);

   QList <QString> paths;
   QVariant s;
   while (query.next()) {
       s=query.value(0);
       paths.append(s.toString());
        }
   //db.close();
   return paths;
}
// section -64--88-0-102-13253627:128108a3c64:-8000:0000000000001166 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

FileJournal::~FileJournal()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-2--790db018:1282222c9e8:-8000:000000000000126B begin
{
    db.removeDatabase("DROPBOX");
    //qt_message_output(QtDebugMsg,"Destroyed");
}
// section 127-0-0-2--790db018:1282222c9e8:-8000:000000000000126B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

