#include "SystemCall.h"


    /* {src_lang=cpp}*/



SystemCall::SystemCall()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-329f1453:127709019c8:-8000:0000000000001160 begin
{

}
// section -64--88-56-1-329f1453:127709019c8:-8000:0000000000001160 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

QString SystemCall::execute()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--615e167d:1276800d166:-8000:00000000000011F0 begin
{
    start(this->command);
    if(waitForReadyRead(1000))
        this->output=(readAll()+readAllStandardOutput()+readAllStandardError());
    this->close();
    return this->output;

}
// section -64--88-56-1--615e167d:1276800d166:-8000:00000000000011F0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

QString SystemCall::execute(QString command)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--615e167d:1276800d166:-8000:00000000000011F6 begin
{
    start(command);
    QString mypid;
    if (waitForStarted(500)){
        mypid=QString::number(pid());
        //qt_message_output(QtWarningMsg,"Execution pid is "+mypid.toLatin1());
    }
    if(waitForReadyRead(500))
        this->output=(readAll()+readAllStandardOutput()+readAllStandardError());


    //this->close();
    return mypid;

}
// section -64--88-56-1--615e167d:1276800d166:-8000:00000000000011F6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void SystemCall::openURL(QString url)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-329f1453:127709019c8:-8000:0000000000001158 begin
{
    startDetached(this->browser+ " " + url);
}
// section -64--88-56-1-329f1453:127709019c8:-8000:0000000000001158 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

QString SystemCall::executeDetached(QString command)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--615e167d:1276800d166:-8000:00000000000011F6 begin
{
    startDetached(command);
    QString mypid;
    if (waitForStarted(500)){
        mypid=QString::number(pid());
        //qt_message_output(QtWarningMsg,"Execution pid is "+mypid.toLatin1());
    }
    return QString::number(pid());

}
